//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventAttendanceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAttendance
    {
        public int AttendanceId { get; set; }
        public string EventTitle { get; set; }
        public string SessionDesc { get; set; }
        public System.DateTime AttendeeLoginTime { get; set; }
        public string AttendeeName { get; set; }
        public string AttendeeSID { get; set; }
        public int AttendeeCampusId { get; set; }
        public string DrinkCount { get; set; }
    }
}
